### ISSUE TITLE
Allow `ZarfInitConfig` to be versioned outside of being tied to binary version

### ISSUE THREAD

**Issue by a1994sc** [zarf-dev/zarf#3148]
### Is your feature request related to a problem? Please describe.

> So we are running RKE2 in an air-gapped environment, so I'm having to write a custom `zarf-init` that is responsible for installing `rook-ceph` into the cluster... so because the init package version is tied to the binary used by the pipeline, when we upgrade ceph from `1.15.3` -> `1.15.4` we would need to override the version we already have published...

### Describe the solution you'd like

- **Given** when `.metadata.version` is defined in a `ZarfInitConfig` Package
- **Then** use that as the package version for the init package
- **Else** default to using the binary version if not present

### Additional context
`zarf init` would also need to accept an option path argument to allow passing in a different `zarf-init` package, but still have the default behavior to search for `zarf-init-<arch>-<version>.tar.zst`

**Comment by hawk87** [comment]
I think the problem is still there. I'd like to version the init package too, I'm having the same problem that you correctly described.

I'm using zarf v0.43.1 and if the package is not named as `zarf-init-<arch>-<version>.tar.zst`, zarf will try to download it, no matter what.

Here we call the `GetInitPackageName` func:
[src/cmd/initialize.go](https://github.com/zarf-dev/zarf/blob/09c41a13112727cc08a2289ead4b16eb895587f0/src/cmd/initialize.go#L46)

And the `GetInitPackageName` function will always return something related to CLI version
https://github.com/zarf-dev/zarf/blob/09c41a13112727cc08a2289ead4b16eb895587f0/src/pkg/packager/sources/utils.go#L157

If we want to have the init package version in the name of the file that relates to the ZarfInitPackage `metadata.version`, I think that we can fix it with `pkg.Metadata.Version`. Something like:
```
// GetInitPackageName returns the formatted name of the init package.
func GetInitPackageName() string {
	// No package has been loaded yet so lookup GetArch() with no package info
	arch := config.GetArch()
        if pkg.Metadata.Version == "" {
	     return fmt.Sprintf("zarf-init-%s-%s.tar.zst", arch, config.CLIVersion)
        } else {
             return fmt.Sprintf("zarf-init-%s-%s.tar.zst", arch, pkg.Metadata.Version)
        }
}
```

This way we might feed any "custom versioned" init package to `zarf init` command. Let me know if I've missed anything, I'm open to discussion.
Thanks for any feedback!

**Comment by a1994sc** [comment]
So it is possible to deploy a zarf init package by using the `zarf package deploy`. This still does all the checks for creating the zarf state and what not

**Comment by a1994sc** [comment]
Yea, I think it got lost when I did force pushes to my branch; but Austin gave very similar advice so I'm more than happy to pass it along!
